import prisma from "@/lib/db";
import type { GscIndexStatus, Prisma, SeoPageType } from "@prisma/client";
import {
  SEO_TEMPLATES,
  getSeoTemplate,
  parseSeoConfig,
  type SeoPageConfig,
} from "./seo-templates";
import { logger } from "@/lib/logger";

export type SeoPageListItem = {
  id: string;
  slug: string;
  title: string;
  pageType: SeoPageType;
  isIndexed: boolean;
  isAutoGenerated: boolean;
  viewCount: number;
  gscIndexStatus: GscIndexStatus;
  gscCoverageState: string | null;
  gscPosition: number | null;
  gscClicks: number;
  gscImpressions: number;
  gscSyncedAt: Date | null;
  updatedAt: Date;
};

export type SeoPageDetail = SeoPageListItem & {
  metaDescription: string;
  h1: string;
  canonicalUrl: string | null;
  ogTitle: string | null;
  ogDescription: string | null;
  ogImage: string | null;
  structuredData: Prisma.JsonValue | null;
  faqs: { id: string; question: string; answer: string; sortOrder: number }[];
};

export async function getSeoPagesList(filters?: {
  q?: string;
  type?: SeoPageType;
}): Promise<SeoPageListItem[]> {
  const where: Prisma.SeoPageWhereInput = {};
  if (filters?.type) where.pageType = filters.type;
  if (filters?.q) {
    where.OR = [
      { slug: { contains: filters.q } },
      { title: { contains: filters.q } },
    ];
  }

  try {
    return await prisma.seoPage.findMany({
      where,
      orderBy: [{ viewCount: "desc" }, { slug: "asc" }],
      select: {
        id: true,
        slug: true,
        title: true,
        pageType: true,
        isIndexed: true,
        isAutoGenerated: true,
        viewCount: true,
        gscIndexStatus: true,
        gscCoverageState: true,
        gscPosition: true,
        gscClicks: true,
        gscImpressions: true,
        gscSyncedAt: true,
        updatedAt: true,
      },
    });
  } catch (error) {
    logger.warn({ error }, "SEO page list lookup failed; returning empty list");
    return [];
  }
}

export async function getSeoPageById(id: string): Promise<SeoPageDetail | null> {
  let page: SeoPageDetail | null = null;
  try {
    page = await prisma.seoPage.findUnique({
      where: { id },
      include: {
        faqs: { orderBy: { sortOrder: "asc" } },
      },
    });
  } catch (error) {
    logger.warn({ error, id }, "SEO page detail lookup failed");
  }
  if (!page) return null;
  return page;
}

export async function getSeoStats() {
  const pages = await getSeoPagesList();
  const indexed = pages.filter((p) => p.isIndexed).length;
  const gscIndexed = pages.filter((p) => p.gscIndexStatus === "INDEXED").length;
  const auto = pages.filter((p) => p.isAutoGenerated).length;
  const totalClicks = pages.reduce((s, p) => s + p.viewCount, 0);
  const gscClicks = pages.reduce((s, p) => s + p.gscClicks, 0);
  const withPosition = pages.filter((p) => p.gscPosition != null && p.gscPosition > 0);
  const avgPosition =
    withPosition.length > 0
      ? Math.round(
          (withPosition.reduce((s, p) => s + (p.gscPosition ?? 0), 0) /
            withPosition.length) *
            10
        ) / 10
      : null;
  const lastGscSync = pages.reduce<Date | null>((latest, p) => {
    if (!p.gscSyncedAt) return latest;
    if (!latest || p.gscSyncedAt > latest) return p.gscSyncedAt;
    return latest;
  }, null);

  return {
    total: pages.length,
    templateTotal: SEO_TEMPLATES.length,
    indexed,
    gscIndexed,
    auto,
    totalClicks,
    gscClicks,
    avgPosition,
    lastGscSync,
  };
}

export async function getIndexedSeoPaths(): Promise<string[]> {
  let dbPages: { slug: string; isIndexed: boolean }[] = [];
  try {
    dbPages = await prisma.seoPage.findMany({
      select: { slug: true, isIndexed: true },
    });
  } catch (error) {
    logger.warn({ error }, "SEO sitemap lookup failed; falling back to templates");
  }
  const dbBySlug = new Map(dbPages.map((p) => [p.slug, p.isIndexed]));
  const paths: string[] = [];

  for (const t of SEO_TEMPLATES) {
    const indexed = dbBySlug.get(t.slug);
    if (indexed === undefined || indexed) {
      paths.push(`/${t.slug}`);
    }
  }

  for (const p of dbPages) {
    if (!p.isIndexed) continue;
    const path = `/${p.slug}`;
    if (!paths.includes(path)) paths.push(path);
  }

  return paths;
}

export async function syncSeoTemplatesFromCatalog(): Promise<{
  created: number;
  updated: number;
  skipped: number;
}> {
  let created = 0;
  let updated = 0;
  let skipped = 0;
  const now = new Date();

  for (const t of SEO_TEMPLATES) {
    const existing = await prisma.seoPage.findUnique({
      where: { slug: t.slug },
      select: { id: true, isAutoGenerated: true },
    });

    if (!existing) {
      await prisma.seoPage.create({
        data: {
          slug: t.slug,
          pageType: t.pageType,
          title: t.title,
          metaDescription: t.metaDescription,
          h1: t.h1,
          structuredData: (t.config ?? {}) as Prisma.InputJsonValue,
          isAutoGenerated: true,
          isIndexed: true,
          lastGeneratedAt: now,
        },
      });
      created++;
      continue;
    }

    if (!existing.isAutoGenerated) {
      skipped++;
      continue;
    }

    await prisma.seoPage.update({
      where: { id: existing.id },
      data: {
        pageType: t.pageType,
        title: t.title,
        metaDescription: t.metaDescription,
        h1: t.h1,
        structuredData: (t.config ?? {}) as Prisma.InputJsonValue,
        lastGeneratedAt: now,
      },
    });
    updated++;
  }

  return { created, updated, skipped };
}

export function resolveSeoConfigFromRecord(
  structuredData: Prisma.JsonValue | null,
  slug: string
): SeoPageConfig {
  const fromDb = parseSeoConfig(structuredData);
  if (Object.keys(fromDb).length > 0) return fromDb;
  return getSeoTemplate(slug)?.config ?? {};
}
