import prisma from "@/lib/db";
import type { Prisma, SeoPageType } from "@prisma/client";
import {
  getSeoTemplate,
  parseSeoConfig,
  SEO_TEMPLATES,
  type SeoPageConfig,
} from "@/modules/admin/seo-templates";
import { logger } from "@/lib/logger";

export type ResolvedSeoPage = {
  id?: string;
  slug: string;
  pageType: SeoPageType;
  title: string;
  metaDescription: string;
  h1: string;
  isIndexed: boolean;
  isAutoGenerated: boolean;
  canonicalUrl?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  ogImage?: string | null;
  config: SeoPageConfig;
  faqs: { question: string; answer: string }[];
};

type SeoPageWithFaqs = Prisma.SeoPageGetPayload<{
  include: { faqs: { orderBy: { sortOrder: "asc" } } };
}>;

export async function getAllSeoSlugs(): Promise<string[]> {
  let db: { slug: string }[] = [];
  try {
    db = await prisma.seoPage.findMany({ select: { slug: true } });
  } catch (error) {
    logger.warn({ error }, "SEO slug lookup failed; falling back to templates");
  }
  const set = new Set<string>([
    ...SEO_TEMPLATES.map((t) => t.slug),
    ...db.map((p) => p.slug),
  ]);
  return [...set];
}

export async function resolveSeoPage(slug: string): Promise<ResolvedSeoPage | null> {
  let db: SeoPageWithFaqs | null = null;
  try {
    db = await prisma.seoPage.findUnique({
      where: { slug },
      include: { faqs: { orderBy: { sortOrder: "asc" } } },
    });
  } catch (error) {
    logger.warn({ error, slug }, "SEO page lookup failed; falling back to templates");
  }

  if (db) {
    return {
      id: db.id,
      slug: db.slug,
      pageType: db.pageType,
      title: db.title,
      metaDescription: db.metaDescription,
      h1: db.h1,
      isIndexed: db.isIndexed,
      isAutoGenerated: db.isAutoGenerated,
      canonicalUrl: db.canonicalUrl,
      ogTitle: db.ogTitle,
      ogDescription: db.ogDescription,
      ogImage: db.ogImage,
      config: resolveConfig(db.structuredData, slug),
      faqs: db.faqs.map((f) => ({ question: f.question, answer: f.answer })),
    };
  }

  const template = getSeoTemplate(slug);
  if (!template) return null;

  return {
    slug: template.slug,
    pageType: template.pageType,
    title: template.title,
    metaDescription: template.metaDescription,
    h1: template.h1,
    isIndexed: true,
    isAutoGenerated: true,
    config: template.config ?? {},
    faqs: [],
  };
}

function resolveConfig(structuredData: unknown, slug: string): SeoPageConfig {
  const fromDb = parseSeoConfig(structuredData);
  if (Object.keys(fromDb).length > 0) return fromDb;
  return getSeoTemplate(slug)?.config ?? {};
}

export async function incrementSeoPageView(slug: string): Promise<void> {
  try {
    await prisma.seoPage.updateMany({
      where: { slug },
      data: { viewCount: { increment: 1 } },
    });
  } catch {
    // non-blocking
  }
}
